In [1]:
import pandas as pd

In [3]:
customers = pd.read_csv("customers.csv")

customers.head()

,customer_id,city,age_group,customer_segment,acquisition_channel,registration_date
0,C000001,Madinah,55+,Loyal,Paid Search,2024-11-26
1,C000002,Jeddah,55+,Regular,Marketplace,2023-03-16
2,C000003,Khobar,45-54,Regular,Organic Search,2024-08-05
3,C000004,Makkah,25-34,New,Social Media,2023-08-20
4,C000005,Riyadh,35-44,Regular,Email,2023-08-16

In [4]:
products = pd.read_csv("products.csv")
orders = pd.read_csv("orders.csv")
order_items = pd.read_csv("order_items.csv")
deliveries = pd.read_csv("deliveries.csv")
returns = pd.read_csv("returns.csv")
warehouses = pd.read_csv("warehouses.csv")
marketing_channels = pd.read_csv("marketing_channels.csv")

In [5]:
print("Customers:", customers.shape)
print("Products:", products.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Deliveries:", deliveries.shape)
print("Returns:", returns.shape)
print("Warehouses:", warehouses.shape)
print("Marketing Channels:", marketing_channels.shape)

Customers: (25000, 6)
Products: (500, 8)
Orders: (120000, 7)
Order Items: (180047, 8)
Deliveries: (120000, 7)
Returns: (6643, 5)
Warehouses: (5, 4)
Marketing Channels: (7, 3)

In [6]:
print("CUSTOMERS")
print(customers.isna().sum())

print("\nPRODUCTS")
print(products.isna().sum())

print("\nORDERS")
print(orders.isna().sum())

print("\nORDER ITEMS")
print(order_items.isna().sum())

print("\nDELIVERIES")
print(deliveries.isna().sum())

print("\nRETURNS")
print(returns.isna().sum())

CUSTOMERS
customer_id              0
city                   120
age_group                0
customer_segment         0
acquisition_channel      0
registration_date        0
dtype: int64

PRODUCTS
product_id       0
category         0
brand            8
cost             0
selling_price    0
supplier         0
warehouse        0
stock_level      0
dtype: int64

ORDERS
order_id             0
customer_id          0
order_datetime       0
city                 0
marketing_channel    0
payment_method       0
order_status         0
dtype: int64

ORDER ITEMS
order_id         0
product_id       0
quantity         0
unit_price      40
unit_cost        0
discount_pct    40
net_sales        0
gross_profit     0
dtype: int64

DELIVERIES
order_id           0
warehouse          0
delivery_method    0
promised_days      0
actual_days        0
delivery_status    0
shipping_cost      0
dtype: int64

RETURNS
return_id        0
order_id         0
return_date      0
return_reason    0
refund_amount    0
dtype: int64

In [7]:
print("Customers duplicates:", customers.duplicated().sum())
print("Products duplicates:", products.duplicated().sum())
print("Orders duplicates:", orders.duplicated().sum())
print("Order Items duplicates:", order_items.duplicated().sum())
print("Deliveries duplicates:", deliveries.duplicated().sum())
print("Returns duplicates:", returns.duplicated().sum())

Customers duplicates: 0
Products duplicates: 0
Orders duplicates: 0
Order Items duplicates: 0
Deliveries duplicates: 0
Returns duplicates: 0

In [8]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          25000 non-null  str
 1   city                 24880 non-null  str
 2   age_group            25000 non-null  str
 3   customer_segment     25000 non-null  str
 4   acquisition_channel  25000 non-null  str
 5   registration_date    25000 non-null  str
dtypes: str(6)
memory usage: 1.1 MB

In [9]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     500 non-null    str
 1   category       500 non-null    str
 2   brand          492 non-null    str
 3   cost           500 non-null    float64
 4   selling_price  500 non-null    float64
 5   supplier       500 non-null    str
 6   warehouse      500 non-null    str
 7   stock_level    500 non-null    int64
dtypes: float64(2), int64(1), str(5)
memory usage: 31.4 KB

In [10]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   order_id           120000 non-null  str
 1   customer_id        120000 non-null  str
 2   order_datetime     120000 non-null  str
 3   city               120000 non-null  str
 4   marketing_channel  120000 non-null  str
 5   payment_method     120000 non-null  str
 6   order_status       120000 non-null  str
dtypes: str(7)
memory usage: 6.4 MB

In [11]:
orders["order_datetime"].head()

0    2025-07-19 12:00:00
1    2025-12-20 15:00:00
2    2024-04-11 23:00:00
3    2024-12-14 07:00:00
4    2024-06-21 20:00:00
Name: order_datetime, dtype: str

In [12]:
orders["order_datetime"] = pd.to_datetime(orders["order_datetime"])

In [13]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   order_id           120000 non-null  str
 1   customer_id        120000 non-null  str
 2   order_datetime     120000 non-null  datetime64[us]
 3   city               120000 non-null  str
 4   marketing_channel  120000 non-null  str
 5   payment_method     120000 non-null  str
 6   order_status       120000 non-null  str
dtypes: datetime64[us](1), str(6)
memory usage: 6.4 MB

In [14]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     500 non-null    str
 1   category       500 non-null    str
 2   brand          492 non-null    str
 3   cost           500 non-null    float64
 4   selling_price  500 non-null    float64
 5   supplier       500 non-null    str
 6   warehouse      500 non-null    str
 7   stock_level    500 non-null    int64
dtypes: float64(2), int64(1), str(5)
memory usage: 31.4 KB

In [15]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 180047 entries, 0 to 180046
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      180047 non-null  str
 1   product_id    180047 non-null  str
 2   quantity      180047 non-null  int64
 3   unit_price    180007 non-null  float64
 4   unit_cost     180047 non-null  float64
 5   discount_pct  180007 non-null  float64
 6   net_sales     180047 non-null  float64
 7   gross_profit  180047 non-null  float64
dtypes: float64(5), int64(1), str(2)
memory usage: 11.0 MB

In [16]:
deliveries.info()

<class 'pandas.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   order_id         120000 non-null  str
 1   warehouse        120000 non-null  str
 2   delivery_method  120000 non-null  str
 3   promised_days    120000 non-null  int64
 4   actual_days      120000 non-null  int64
 5   delivery_status  120000 non-null  str
 6   shipping_cost    120000 non-null  float64
dtypes: float64(1), int64(2), str(4)
memory usage: 6.4 MB

In [17]:
returns.info()

<class 'pandas.DataFrame'>
RangeIndex: 6643 entries, 0 to 6642
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      6643 non-null   str
 1   order_id       6643 non-null   str
 2   return_date    6643 non-null   str
 3   return_reason  6643 non-null   str
 4   refund_amount  6643 non-null   float64
dtypes: float64(1), str(4)
memory usage: 259.6 KB

In [18]:
warehouses.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   warehouse_id    5 non-null      str
 1   warehouse_name  5 non-null      str
 2   city            5 non-null      str
 3   capacity_units  5 non-null      int64
dtypes: int64(1), str(3)
memory usage: 292.0 bytes

In [19]:
marketing_channels.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   channel_id    7 non-null      str
 1   channel_name  7 non-null      str
 2   channel_type  7 non-null      str
dtypes: str(3)
memory usage: 300.0 bytes

In [20]:
returns["return_date"] = pd.to_datetime(returns["return_date"])

In [21]:
returns.info()

<class 'pandas.DataFrame'>
RangeIndex: 6643 entries, 0 to 6642
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      6643 non-null   str
 1   order_id       6643 non-null   str
 2   return_date    6643 non-null   datetime64[us]
 3   return_reason  6643 non-null   str
 4   refund_amount  6643 non-null   float64
dtypes: datetime64[us](1), float64(1), str(3)
memory usage: 259.6 KB

In [22]:
customers["city"] = customers["city"].fillna("Unknown")

In [23]:
customers["city"].isna().sum()

np.int64(0)

In [24]:
customers["city"].value_counts()

city
Riyadh     8506
Jeddah     5386
Dammam     2753
Makkah     2008
Madinah    1779
Khobar     1755
Abha       1460
Tabuk      1233
Unknown     120
Name: count, dtype: int64

In [25]:
products["brand"] = products["brand"].fillna("Unknown")

In [26]:
products["brand"].isna().sum()

np.int64(0)

In [27]:
order_items["discount_pct"] = order_items["discount_pct"].fillna(0)

In [28]:
order_items["discount_pct"].isna().sum()

np.int64(0)

In [ ]:
order_items["unit_price"] = order_items["unit_price"].fillna(
    order_items["product_id"].map(
        products.set_index("product_id")["selling_price"]
    )
)

In [30]:
order_items["unit_price"].isna().sum()

np.int64(0)

In [31]:
order_items["net_sales"] = (
    order_items["quantity"]
    * order_items["unit_price"]
    * (1 - order_items["discount_pct"] / 100)
).round(2)

order_items["gross_profit"] = (
    order_items["net_sales"]
    - (order_items["quantity"] * order_items["unit_cost"])
).round(2)

In [32]:
order_items[["quantity", "unit_price", "discount_pct", "net_sales", "gross_profit"]].head()

   quantity  unit_price  discount_pct  net_sales  gross_profit
0         1       55.34           0.0      55.34         22.98
1         3      130.62           0.0     391.86        177.93
2         2      190.56          10.0     343.01        100.19
3         1      270.32          25.0     202.74         45.70
4         2      110.57           0.0     221.14         61.46

In [34]:
# Calculate the main business KPIs for Tamkeen Market

# Total revenue generated from all order items
total_revenue = order_items["net_sales"].sum()

# Total profit after product costs
total_profit = order_items["gross_profit"].sum()

# Number of unique orders
total_orders = orders["order_id"].nunique()

# Number of unique customers
total_customers = customers["customer_id"].nunique()

# Number of products in the catalog
total_products = products["product_id"].nunique()

# Display the KPIs
print(f"Revenue: SAR {total_revenue:,.2f}")
print(f"Profit: SAR {total_profit:,.2f}")
print(f"Orders: {total_orders:,}")
print(f"Customers: {total_customers:,}")
print(f"Products: {total_products:,}")

Revenue: SAR 36,867,433.62
Profit: SAR 10,521,748.12
Orders: 120,000
Customers: 25,000
Products: 500

In [35]:
# Connect orders with order items so we can analyze sales by city
sales = order_items.merge(
    orders[["order_id", "customer_id", "city", "order_datetime"]],
    on="order_id",
    how="left"
)

# Calculate revenue and profit by city
city_performance = (
    sales.groupby("city")
    .agg(
        revenue=("net_sales", "sum"),
        profit=("gross_profit", "sum"),
        orders=("order_id", "nunique")
    )
    .sort_values("revenue", ascending=False)
)

city_performance

             revenue      profit  orders
city
Riyadh   12651548.06  3608475.30   41276
Jeddah    7938571.71  2256293.91   25806
Dammam    4038772.28  1161283.10   13248
Makkah    2972194.30   848523.52    9651
Madinah   2655986.19   762512.13    8556
Khobar    2591062.21   735908.42    8439
Abha      2170763.82   615939.04    7021
Tabuk     1848535.05   532812.70    6003

In [36]:
# Add product information to our sales data
sales_products = sales.merge(
    products[["product_id", "category", "brand"]],
    on="product_id",
    how="left"
)

# Calculate performance by product category
category_performance = (
    sales_products.groupby("category")
    .agg(
        revenue=("net_sales", "sum"),
        profit=("gross_profit", "sum"),
        orders=("order_id", "nunique"),
        units_sold=("quantity", "sum")
    )
    .sort_values("revenue", ascending=False)
)

category_performance

                           revenue      profit  orders  units_sold
category
Mobile Accessories      6149750.76  1765035.43   27106       57633
Beauty & Personal Care  5679638.10  1676467.66   25595       54230
Groceries               5427110.57  1654566.42   25009       53147
Fashion                 5334095.23  1531920.94   24956       53152
Sports & Fitness        5260923.15  1417263.18   24210       51380
Electronics             4532614.93  1169294.99   22325       47066
Home & Kitchen          4483300.88  1307199.50   20754       43811

In [37]:
# Extract the month from each order date
sales["month"] = sales["order_datetime"].dt.to_period("M")

# Calculate monthly revenue and profit
monthly_performance = (
    sales.groupby("month")
    .agg(
        revenue=("net_sales", "sum"),
        profit=("gross_profit", "sum"),
        orders=("order_id", "nunique")
    )
    .sort_index()
)

monthly_performance

            revenue     profit  orders
month
2024-01  1592275.24  456951.74    5077
2024-02  1446884.57  408851.30    4789
2024-03  1575880.09  450311.33    5086
2024-04  1522445.16  438457.39    5020
2024-05  1605479.44  453184.63    5181
2024-06  1528550.54  435991.06    4928
2024-07  1554305.76  443104.59    4989
2024-08  1586195.88  454843.52    5072
2024-09  1524443.40  433803.63    4935
2024-10  1565228.83  447764.42    5107
2024-11  1568951.02  446338.09    5009
2024-12  1542930.10  442304.18    5105
2025-01  1567982.47  447856.58    5057
2025-02  1404767.72  397379.72    4598
2025-03  1573615.32  450342.51    5149
2025-04  1490559.63  424990.41    4847
2025-05  1546927.32  442825.18    5076
2025-06  1550343.82  443442.50    5000
2025-07  1553315.34  444347.79    5146
2025-08  1577854.00  448611.66    5108
2025-09  1474882.36  421130.64    4859
2025-10  1560312.56  445811.42    5084
2025-11  1473482.63  420179.24    4906
2025-12  1479820.42  422924.59    4872

In [38]:
# Calculate customer-level performance
customer_performance = (
    sales.groupby("customer_id")
    .agg(
        revenue=("net_sales", "sum"),
        profit=("gross_profit", "sum"),
        orders=("order_id", "nunique")
    )
    .sort_values("revenue", ascending=False)
)

# Show the top 10 customers by revenue
customer_performance.head(10)

             revenue   profit  orders
customer_id
C021049      6910.49  2253.37      14
C022251      6558.42  2090.73       9
C022272      6537.68  2258.51      11
C014809      6443.91  1701.40      13
C004928      6151.54  1855.49      14
C013006      5949.47  2057.40       7
C024437      5929.50  2165.44      10
C000980      5910.61  1970.11       9
C015734      5809.29  1652.37      11
C021183      5785.49  1675.49       6

In [40]:
# Add marketing channel to the sales dataset
sales = sales.merge(
    orders[["order_id", "marketing_channel"]],
    on="order_id",
    how="left"
)

# Revenue and profit by marketing channel
channel_performance = (
    sales.groupby("marketing_channel")
    .agg(
        revenue=("net_sales", "sum"),
        profit=("gross_profit", "sum"),
        orders=("order_id", "nunique")
    )
    .sort_values("revenue", ascending=False)
)

display(channel_performance)

                      revenue      profit  orders
marketing_channel
Organic Search     8238097.24  2348307.29   26609
Direct             6650939.19  1892901.89   21547
Social Media       6338241.61  1803314.13   20539
Paid Search        5800777.14  1654228.78   19041
Email              3665271.36  1053549.07   11897
Marketplace        3278713.96   939764.69   10740
Affiliate          2895393.12   829682.27    9627

In [41]:
# Average order value
average_order_value = sales.groupby("order_id")["net_sales"].sum().mean()

# Overall profit margin
profit_margin = (total_profit / total_revenue) * 100

# Return rate
return_rate = (returns["order_id"].nunique() / total_orders) * 100

print(f"Average Order Value: SAR {average_order_value:,.2f}")
print(f"Profit Margin: {profit_margin:.2f}%")
print(f"Return Rate: {return_rate:.2f}%")

Average Order Value: SAR 307.23
Profit Margin: 28.54%
Return Rate: 5.54%

In [42]:
# Export cleaned tables for SQL, Power BI, and Excel
customers.to_csv("customers_clean.csv", index=False)
products.to_csv("products_clean.csv", index=False)
orders.to_csv("orders_clean.csv", index=False)
order_items.to_csv("order_items_clean.csv", index=False)
deliveries.to_csv("deliveries_clean.csv", index=False)
returns.to_csv("returns_clean.csv", index=False)
warehouses.to_csv("warehouses_clean.csv", index=False)
marketing_channels.to_csv("marketing_channels_clean.csv", index=False)

print("All cleaned datasets exported successfully.")

All cleaned datasets exported successfully.

In [43]:
import sqlite3

# Create the SQLite database
conn = sqlite3.connect("tamkeen_market.db")

# Load all cleaned tables into SQLite
customers.to_sql("customers", conn, if_exists="replace", index=False)
products.to_sql("products", conn, if_exists="replace", index=False)
orders.to_sql("orders", conn, if_exists="replace", index=False)
order_items.to_sql("order_items", conn, if_exists="replace", index=False)
deliveries.to_sql("deliveries", conn, if_exists="replace", index=False)
returns.to_sql("returns", conn, if_exists="replace", index=False)
warehouses.to_sql("warehouses", conn, if_exists="replace", index=False)
marketing_channels.to_sql("marketing_channels", conn, if_exists="replace", index=False)

print("SQLite database created successfully.")

SQLite database created successfully.

In [44]:
# Check that all tables were created in SQLite
tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

tables

                 name
0           customers
1            products
2              orders
3         order_items
4          deliveries
5             returns
6          warehouses
7  marketing_channels

In [45]:
# Executive KPIs using SQL
kpis = pd.read_sql_query("""
SELECT
    ROUND(SUM(net_sales), 2) AS total_revenue,
    ROUND(SUM(gross_profit), 2) AS total_profit,
    COUNT(DISTINCT order_id) AS total_orders
FROM order_items;
""", conn)

kpis

   total_revenue  total_profit  total_orders
0    36867433.62   10521748.12        120000

In [46]:
# Revenue, profit, and orders by city
city_sql = pd.read_sql_query("""
SELECT
    o.city,
    ROUND(SUM(oi.net_sales), 2) AS revenue,
    ROUND(SUM(oi.gross_profit), 2) AS profit,
    COUNT(DISTINCT o.order_id) AS orders
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY o.city
ORDER BY revenue DESC;
""", conn)

city_sql

      city      revenue      profit  orders
0   Riyadh  12651548.06  3608475.30   41276
1   Jeddah   7938571.71  2256293.91   25806
2   Dammam   4038772.28  1161283.10   13248
3   Makkah   2972194.30   848523.52    9651
4  Madinah   2655986.19   762512.13    8556
5   Khobar   2591062.21   735908.42    8439
6     Abha   2170763.82   615939.04    7021
7    Tabuk   1848535.05   532812.70    6003

In [47]:
# Monthly revenue and profit
monthly_sql = pd.read_sql_query("""
SELECT
    strftime('%Y-%m', o.order_datetime) AS month,
    ROUND(SUM(oi.net_sales), 2) AS revenue,
    ROUND(SUM(oi.gross_profit), 2) AS profit
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY month
ORDER BY month;
""", conn)

# Category performance
category_sql = pd.read_sql_query("""
SELECT
    p.category,
    ROUND(SUM(oi.net_sales), 2) AS revenue,
    ROUND(SUM(oi.gross_profit), 2) AS profit,
    SUM(oi.quantity) AS units_sold
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY revenue DESC;
""", conn)

print("MONTHLY PERFORMANCE")
display(monthly_sql)

print("CATEGORY PERFORMANCE")
display(category_sql)

MONTHLY PERFORMANCE

      month     revenue     profit
0   2024-01  1592275.24  456951.74
1   2024-02  1446884.57  408851.30
2   2024-03  1575880.09  450311.33
3   2024-04  1522445.16  438457.39
4   2024-05  1605479.44  453184.63
5   2024-06  1528550.54  435991.06
6   2024-07  1554305.76  443104.59
7   2024-08  1586195.88  454843.52
8   2024-09  1524443.40  433803.63
9   2024-10  1565228.83  447764.42
10  2024-11  1568951.02  446338.09
11  2024-12  1542930.10  442304.18
12  2025-01  1567982.47  447856.58
13  2025-02  1404767.72  397379.72
14  2025-03  1573615.32  450342.51
15  2025-04  1490559.63  424990.41
16  2025-05  1546927.32  442825.18
17  2025-06  1550343.82  443442.50
18  2025-07  1553315.34  444347.79
19  2025-08  1577854.00  448611.66
20  2025-09  1474882.36  421130.64
21  2025-10  1560312.56  445811.42
22  2025-11  1473482.63  420179.24
23  2025-12  1479820.42  422924.59

CATEGORY PERFORMANCE

                 category     revenue      profit  units_sold
0      Mobile Accessories  6149750.76  1765035.43       57633
1  Beauty & Personal Care  5679638.10  1676467.66       54230
2               Groceries  5427110.57  1654566.42       53147
3                 Fashion  5334095.23  1531920.94       53152
4        Sports & Fitness  5260923.15  1417263.18       51380
5             Electronics  4532614.93  1169294.99       47066
6          Home & Kitchen  4483300.88  1307199.50       43811

In [48]:
# Customer performance
customer_sql = pd.read_sql_query("""
SELECT
    o.customer_id,
    COUNT(DISTINCT o.order_id) AS orders,
    ROUND(SUM(oi.net_sales), 2) AS revenue,
    ROUND(SUM(oi.gross_profit), 2) AS profit
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY o.customer_id
ORDER BY revenue DESC;
""", conn)

customer_sql.head(10)

  customer_id  orders  revenue   profit
0     C021049      14  6910.49  2253.37
1     C022251       9  6558.42  2090.73
2     C022272      11  6537.68  2258.51
3     C014809      13  6443.91  1701.40
4     C004928      14  6151.54  1855.49
5     C013006       7  5949.47  2057.40
6     C024437      10  5929.50  2165.44
7     C000980       9  5910.61  1970.11
8     C015734      11  5809.29  1652.37
9     C021183       6  5785.49  1675.49

In [49]:
# Return analysis
return_sql = pd.read_sql_query("""
SELECT
    return_reason,
    COUNT(*) AS returns,
    ROUND(SUM(refund_amount), 2) AS refunds
FROM returns
GROUP BY return_reason
ORDER BY returns DESC;
""", conn)

# Delivery performance
delivery_sql = pd.read_sql_query("""
SELECT
    delivery_status,
    COUNT(*) AS deliveries,
    ROUND(AVG(actual_days), 2) AS avg_delivery_days,
    ROUND(AVG(shipping_cost), 2) AS avg_shipping_cost
FROM deliveries
GROUP BY delivery_status
ORDER BY deliveries DESC;
""", conn)

print("RETURN ANALYSIS")
display(return_sql)

print("DELIVERY PERFORMANCE")
display(delivery_sql)

RETURN ANALYSIS

     return_reason  returns    refunds
0    Late Delivery     1409  356686.25
1          Damaged     1351  359316.85
2       Wrong Item     1313  335949.01
3     Changed Mind     1300  336727.88
4  Not as Expected     1270  328913.04

DELIVERY PERFORMANCE

  delivery_status  deliveries  avg_delivery_days  avg_shipping_cost
0       Delivered      100843               3.07              26.48
1            Late       14446               3.07              26.54
2          Failed        4711               3.03              26.57